// <auto-generated> PlayForge mirror partial. Do not edit. </auto-generated>
using System;
using System.Collections.Generic;
using UnityEngine;
namespace FarEmerald.PlayForge.Extended
{
	public partial class AbilityData
	{
		// Mirrored from: FarEmerald.PlayForge.Ability
		public FarEmerald.PlayForge.GameplayEffect Cooldown;
		public FarEmerald.PlayForge.GameplayEffect Cost;
		public FarEmerald.PlayForge.AbilityDefinition Definition;
		public System.Boolean IgnoreWhenLevelZero;
		public System.Int32 MaxLevel;
		public FarEmerald.PlayForge.AbilityProxySpecification Proxy;
		public System.Int32 StartingLevel;
		public FarEmerald.PlayForge.AbilityTags Tags;
	}
}
