// <auto-generated> PlayForge mirror partial. Do not edit. </auto-generated>
using System;
using System.Collections.Generic;
using UnityEngine;
namespace FarEmerald.PlayForge.Extended
{
	public partial class AttributeSetData
	{
		// Mirrored from: FarEmerald.PlayForge.AttributeSet
		public System.Collections.Generic.List<FarEmerald.PlayForge.AttributeSetElement> Attributes;
		public FarEmerald.PlayForge.EValueCollisionPolicy CollisionResolutionPolicy;
		public System.Collections.Generic.List<FarEmerald.PlayForge.AttributeSet> SubSets;
	}
}
