// <auto-generated> PlayForge mirror partial. Do not edit. </auto-generated>
using System;
using System.Collections.Generic;
using UnityEngine;
namespace FarEmerald.PlayForge.Extended
{
	public partial class EffectData
	{
		// Mirrored from: FarEmerald.PlayForge.GameplayEffect
		public FarEmerald.PlayForge.GameplayEffectDefinition Definition;
		public FarEmerald.PlayForge.GameplayEffectDurationSpecification DurationSpecification;
		public FarEmerald.PlayForge.GameplayEffectImpactSpecification ImpactSpecification;
		public FarEmerald.PlayForge.TagRequirements SourceRequirements;
		public FarEmerald.PlayForge.GameplayEffectTags Tags;
		public FarEmerald.PlayForge.TagRequirements TargetRequirements;
		public System.Collections.Generic.List<FarEmerald.PlayForge.AbstractEffectWorker> Workers;
	}
}
