// <auto-generated> PlayForge mirror partial. Do not edit. </auto-generated>
using System;
using System.Collections.Generic;
using UnityEngine;
namespace FarEmerald.PlayForge.Extended
{
	public partial class EntityData
	{
		// Mirrored from: FarEmerald.PlayForge.EntityIdentity
		public FarEmerald.PlayForge.EAbilityActivationPolicy ActivationPolicy;
		public System.Boolean AllowDuplicateAbilities;
		public System.Collections.Generic.List<FarEmerald.PlayForge.AbstractAttributeChangeEvent> AttributeChangeEvents;
		public FarEmerald.PlayForge.AttributeSet AttributeSet;
		public FarEmerald.PlayForge.GASIdentityData Identity;
		public System.Collections.Generic.List<FarEmerald.PlayForge.AbstractImpactWorker> ImpactWorkers;
		public System.Int32 MaxAbilities;
		public System.Collections.Generic.List<FarEmerald.PlayForge.Ability> StartingAbilities;
		public System.Collections.Generic.List<FarEmerald.PlayForge.AbstractTagWorker> TagWorkers;
	}
}
