// <auto-generated> PlayForge mirror partial. Do not edit. </auto-generated>
using System;
using System.Collections.Generic;
using UnityEngine;
namespace FarEmerald.PlayForge.Extended
{
	public partial class TagData
	{
		// Mirrored from: FarEmerald.PlayForge.Tag
	}
}
